force-app/main/default/objects/Prodotto__c/Prodotto__c.object-meta.xml
<CustomObject>
    <label>Prodotto</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Numero Prodotto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prodotto__c/fields/Disponibilita__c.field-meta.xml
<CustomField>
    <fullName>Disponibilita__c</fullName>
    <label>Disponibilita</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prodotto__c/fields/Prezzo__c.field-meta.xml
<CustomField>
    <fullName>Prezzo__c</fullName>
    <label>Prezzo</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RigaOrdine__c/RigaOrdine__c.object-meta.xml
<CustomObject>
    <label>RigaOrdine</label>
    <nameField>
        <displayFormat>RO-{000}</displayFormat>
        <label>Numero RigaOrdine</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RigheOrdine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RigaOrdine__c/fields/PrezzoUnitario__c.field-meta.xml
<CustomField>
    <fullName>PrezzoUnitario__c</fullName>
    <label>PrezzoUnitario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RigaOrdine__c/fields/Prodotto__c.field-meta.xml
<CustomField>
    <fullName>Prodotto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prodotto</label>
    <referenceTo>Prodotto__c</referenceTo>
    <relationshipLabel>RigheOrdine</relationshipLabel>
    <relationshipName>RigheOrdine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RigaOrdine__c/fields/Quantita__c.field-meta.xml
<CustomField>
    <fullName>Quantita__c</fullName>
    <label>Quantita</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RigaOrdineService.cls
public class RigaOrdineService {

    public static void popolaPrezzoUnitario (List<RigaOrdine__c> righe){
    
        Set<Id> productIds = new Set<Id>();
        
        for (RigaOrdine__c r:righe){
        
            if (r.Prodotto__c != null) {
                productIds.add(r.Prodotto__c);
            }
        }

        if (productIds.isEmpty()) return;
        
        Map<Id, Prodotto__c> prodottiMap = new Map<Id, Prodotto__c>(
            [SELECT Id, Prezzo__c FROM Prodotto__c WHERE Id IN :productIds]
        );
        
        for (RigaOrdine__c r : righe) {
            if (r.Prodotto__c != null && prodottiMap.containsKey(r.Prodotto__c)) {
                r.PrezzoUnitario__c = prodottiMap.get(r.Prodotto__c).Prezzo__c;
            }
        }

    }
    
    public static void controllaDisponibilita(List<RigaOrdine__c> righe) {

        Set<Id> productIds = new Set<Id>();

        for (RigaOrdine__c r : righe) {
            if (r.Prodotto__c != null) {
                productIds.add(r.Prodotto__c);
            }
        }

        if (productIds.isEmpty()) return;

        Map<Id, Prodotto__c> prodottiMap = new Map<Id, Prodotto__c>(
            [SELECT Id, Disponibilita__c
             FROM Prodotto__c
             WHERE Id IN :productIds]
        );

        for (RigaOrdine__c r : righe) {
            if (
                prodottiMap.containsKey(r.Prodotto__c) &&
                r.Quantita__c != null
            ) {
                Prodotto__c p = prodottiMap.get(r.Prodotto__c);

                if (p.Disponibilita__c != null &&
                    r.Quantita__c > p.Disponibilita__c) {

                    r.addError(
                        'Quantità superiore alla disponibilità del prodotto.'
                    );
                }
            }
}
}

public static void aggiornaDisponibilita(List<RigaOrdine__c> righe) {

    Map<Id, Decimal> quantitaPerProdotto = new Map<Id, Decimal>();

    for (RigaOrdine__c r : righe) {
        if (r.Prodotto__c != null && r.Quantita__c != null) {

            if (!quantitaPerProdotto.containsKey(r.Prodotto__c)) {
                quantitaPerProdotto.put(r.Prodotto__c, 0);
            }

            quantitaPerProdotto.put(
                r.Prodotto__c,
                quantitaPerProdotto.get(r.Prodotto__c) + r.Quantita__c
            );
        }
    }

    if (quantitaPerProdotto.isEmpty()) return;

    List<Prodotto__c> prodottiDaAggiornare =
        [SELECT Id, Disponibilita__c
         FROM Prodotto__c
         WHERE Id IN :quantitaPerProdotto.keySet()];

    for (Prodotto__c p : prodottiDaAggiornare) {

        Decimal qtaOrdinata = quantitaPerProdotto.get(p.Id);

        if (p.Disponibilita__c == null) {
            p.Disponibilita__c = 0;
        }

        p.Disponibilita__c -= qtaOrdinata;
    }

    update prodottiDaAggiornare;
}

}